apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod
  name: testpod
spec:
  containers:
  - image: praqma/network-multitool
    name: testpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
